### ISSUE TITLE
Styles system

### ISSUE THREAD

**Issue by Rorkh** [Defaultik/DefaultUILibary#2]
Maybe, styles system must be implemented to change main colors, and, maybe, fonts?
Like
```lua
DLib.RegisterSkin("dark-one", {
   TitleText = Color(...),
   ...
}
DLib.ApplySkin("dark-one")
```

I can do this tomorrow.
P.S: Library, а не libary

**Comment by Defaultik** [comment]
What's the practical point of Style System?

**Comment by Rorkh** [comment]
> What's the practical point of Style System?

Ability to change UI colors without editing core file, obviously.

**Comment by Defaultik** [comment]
i can do it without style system
